substitutions:
  devicename: livingroom
  upper_devicename: Livingroom

esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret hass_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .chrisdower.com
  manual_ip:
    static_ip: 192.168.10.50
    gateway: 192.168.10.0
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename} Fallback Hotspot"
    password: !secret AP_PASS

captive_portal:

mqtt:
  log_topic: "home/${devicename}/sensor"
  broker: !secret mqtt_broker
  discovery: True
  username: homeassistant
  password: !secret hass_password
  
i2c:
  sda: 33
  scl: 32
  scan: True
  id: bus_a

#DHT or bme280, DS18B20 Sensor
sensor:
  - platform: bme280
    i2c_id: bus_a
    address: 0x77
    update_interval: 60s
    temperature:
      name: "${upper_devicename} Temperature"
      oversampling: 16x
    humidity:
      name: "${upper_devicename} Humidity"
    pressure:
      name: "${upper_devicename} Pressure"

