substitutions:
  devicename: bedroom
  upper_devicename: Bedroom

esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s

api:
  password: !secret hass_password

wifi:
  ssid: !secret SSID
  password: !secret SSID_PASS
  manual_ip:
    static_ip: 192.168.10.230
    gateway: 192.168.10.0
    subnet: 255.255.255.0
  ap:
    ssid: "${upper_devicename}2 Fallback Hotspot"
    password: !secret AP_PASS
    
captive_portal:
    
# Enable logging
logger:

mqtt:
  log_topic: "home/${devicename}/sensor"
  broker: 192.168.10.214
  discovery: True
  username: homeassistant
  password: !secret hass_password

ota:
  safe_mode: True
  password: !secret ota_password
  
#deep_sleep:
#  run_duration: 90s
#  sleep_duration: 5min

# BLE RSSI Sensor
esp32_ble_tracker:

#DHT or bme280, DS18B20 Sensor
sensor:
  - platform: dht
    pin: GPIO26
    model: DHT22
    temperature:
      name: "${upper_devicename} Temperature"
    humidity:
      name: "${upper_devicename} Humidity"
  #- platform: ble_rssi
  #  mac_address: 40:4e:36:7e:04:1f
  #  name: chris_pixel
    
  